server:
  port: 8084
  # ssl:
  #     key-store: keystore.p12
  #     key-store-password: 123456
  #     keyStoreType: PKCS12
  #     keyAlias: tomcat
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/HIS_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
application:
  security:
    jwt:
      secret-key: 0po1YL6SicMrlnChfzYw65PbbM5DU5Xt6cj86jtEtboRVrZ6hP4u6sDxfqTyBmSG
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


# Jasypt Configuration
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: HELLO

aes:
  encryption:
    key: this-is-test-key